extend type Mutation {
    register(input: RegisterInput @spread): SuccessResponse!
        @field(
            resolver: "Modules\\User\\GraphQL\\Mutations\\AuthMutator@register"
        )
    login(input: LoginInput @spread): AuthPayload!
        @field(resolver: "Modules\\User\\GraphQL\\Mutations\\AuthMutator@login")
    sendEmailVerification: SuccessResponse!
        @field(
            resolver: "Modules\\User\\GraphQL\\Mutations\\AuthMutator@sendEmailVerification"
        )
    sendPhoneVerification: SuccessResponse!
        @field(
            resolver: "Modules\\User\\GraphQL\\Mutations\\AuthMutator@sendPhoneVerification"
        )
    verifyEmail(input: VerifyCodeInput @spread): SuccessResponse!
        @field(
            resolver: "Modules\\User\\GraphQL\\Mutations\\AuthMutator@verifyEmail"
        )
    verifyPhone(input: VerifyCodeInput @spread): SuccessResponse!
        @field(
            resolver: "Modules\\User\\GraphQL\\Mutations\\AuthMutator@verifyPhone"
        )
}

input RegisterInput {
    name: String!
    email: String!
    password: String!
    password_confirmation: String!
    phone_code: String!
    phone_number: String!
}

input LoginInput {
    email: String!
    password: String!
}

input VerifyCodeInput {
    code: String!
}

type AuthPayload {
    token: String!
    token_type: String
}
