extend type Mutation {
    register(input: RegisterInput @spread): SuccessResponse!
        @field(
            resolver: "Modules\\User\\GraphQL\\Mutations\\UserMutator@register"
        )
    login(input: LoginInput @spread): AuthPayload!
        @field(resolver: "Modules\\User\\GraphQL\\Mutations\\UserMutator@login")
}

input RegisterInput {
    name: String!
    email: String!
    password: String!
    password_confirmation: String!
    phone_code: String!
    phone_number: String!
}

input LoginInput {
    email: String!
    password: String!
}

type AuthPayload {
    token: String!
    token_type: String
}
