extend type Mutation {
    createMenu(input: CreateMenuInput @spread): SuccessResponse!
    @field(resolver: "Modules\\Menu\\GraphQL\\Mutations\\MenuMutator@create")
    updateMenu(menu_id: ID!, input: UpdateMenuInput @spread): SuccessResponse!
    @field(resolver: "Modules\\Menu\\GraphQL\\Mutations\\MenuMutator@update")
    deleteMenu(menu_id: ID!): SuccessResponse!
    @field(resolver: "Modules\\Menu\\GraphQL\\Mutations\\MenuMutator@delete")
}

input CreateMenuInput {
    menu_name: String!
    menu_slug: String!
    menu_type: MenuType!
    menu_description: String
    menu_price_cents: Float!
    menu_status: MenuStatus
    image: Upload
}

input UpdateMenuInput {
    menu_id: ID!
    menu_name: String
    menu_slug: String
    menu_description: String
    menu_price_cents: Float
    image: Upload
}

enum MenuType {
    ALLDAY @enum(value: "all_day")
    TOAST @enum(value: "toast")
    BITES @enum(value: "bites")
    PIZZA @enum(value: "pizza")
    PASTA @enum(value: "pasta")
    ETCETERA @enum(value: "etcetera")
    SOUP @enum(value: "soup")
    ESPRESSO @enum(value: "espresso")
    FRAPPE @enum(value: "frappe")
    NONCOFFEE @enum(value: "non-coffee")
}

enum MenuStatus {
    ACTIVE
    INACTIVE
}