extend type Mutation {
    addToCart(input: AddToCartInput @spread): SuccessResponse!
    @field(resolver: "Modules\\Cart\\GraphQL\\Mutations\\CartMutator@addToCart")
    removeFromCart(input: RemoveFromCartInput @spread): SuccessResponse!
    @field(resolver: "Modules\\Cart\\GraphQL\\Mutations\\CartMutator@removeFromCart")
    updateCartItem(input: UpdateCartItemInput @spread): SuccessResponse!
    @field(resolver: "Modules\\Cart\\GraphQL\\Mutations\\CartMutator@updateCartItem")
}

input AddToCartInput {
    menu_id: Int!
    quantity: Int!
}

input UpdateCartItemInput {
    id: Int!
    quantity: Int!
}

input RemoveFromCartInput {
    id: Int!
}
